= GemFire Native Labs
2016
:toc:

This repository contains two labs on the subject of the http://gemfire-native.docs.pivotal.io/native/about_native_client_users_guide.html[Gemfire Native Client].

Each lab consists of code and artifacts that represent your starting point, along with instructions that will walk you through the steps necessary to complete each task.

Each lab also comes with a solved version, for reference.

== Environment Setup

We provide a `Vagrantfile` to start up and provision a CentOS VM that can be used to compile and run the labs' source code.

=== Prerequisites

Download:

1. https://www.virtualbox.org[VirtualBox]
2. https://www.vagrantup.com/downloads.html[Vagrant]
3. https://network.pivotal.io/products/pivotal-gemfire/[Pivotal GemFire Native Client for Linux (64-bit)]

Install VirtualBox, Vagrant, and make sure to place the GemFire Native Client zip file in this project's base directory (alongside `Vagrantfile`).

=== Working with Vagrant

* To provision the VM, simply:

  $ vagrant up
+
* You can ssh into your guest OS with:

  $ vagrant ssh
+
* All files in this directory are shared with your guest OS under the folder `/vagrant`

  $ cd /vagrant
+
You'll see a copy of the labs folder in there.
+
The fact that this folder is shared with both the host and guest OS implies that you have the convenience of editing the lab .cpp (and other) files on your host OS, while compiling and running the code on the guest OS.

== Tips

* You will need to know how to access gemfire (which is running on your host) from the guest OS.  This command, invoked on the guest should tell you what that IP address is:

  $ netstat -rn | grep '^0.0.0.0 ' | awk '{print $2}'
+
