= Lab 2: Cross-platform communication using PDX

== Introduction

In this lab you will build a native C++ application that can access data stored in the GemFire cluster by a Java application.  Your application will connect to the same GemFire cluster that you were using in the main "GemFire Developer" course.  You will also need to complete the "Data Serialization" lab in that course since we will rely on the data stored into GemFire from this lab.

*What you will learn:*

* Use PDX serialization mechanism in native C++ client applications

* Working with multiple versions of domain objects in PDX

* Using PdxInstance to get a single field

*Estimated completion time:* 40 minutes

== Instructions

=== Using GemFire PDX Serialization

a. In the Linux VM shell, switch to the lab folder:

  cd /vagrant/labs/lab2-cross-platform

b. In your favorite editor, open and investigate the `PdxInstance.cpp` and `clientPdxInstance.xml` files.  `PdxInstance.cpp` is a simple console application that acts as a GemFire client and stores PDX serialized data in the remote GemFire distributed system.  The `clientPdxInstance.xml` file is a GemFire cache XML file used by `PdxInstance.cpp` to configure GemFire client cache instance.  You will need to fill in the places marked with `"TODO"` in both files in order to complete this lab.  Please refer to the `lab2-cross-platform-solution` folder for the full working version of the application.

c. `(TODO-0)` In `clientPdxInstance.xml` modify the IP address of the GemFire locator that will be used by the native client cache.  Replace the IP address with the IP address of the machine where your test GemFire cluster is running, e.g. your host OS.

d. `(TODO-1)` In `clientPdxInstance.xml`, add the `<pdx>` element and turn on the `read-serialized` flag.  This tells the native client cache to obtain the entries as `PdxInstance` objects and not try to deserialize them automatically when returning to the client application code.

e. `(TODO-2)` Create an instance of the `Person` class to be stored in the GemFire cache using PDX serialization.  It will be used as a source of the `PdxInstance` object fields and can be placed directly on the `main()` procedure stack to simplify memory management.  Please note that the `Person` class is defined and implemented directly at the top of the main `PdxInstance.cpp` application source file.

f. `(TODO-3)` Create `PdxInstanceFactoryPtr` object for the `Person` class.  You should use for that the `createPdxInstanceFactory()` method of the already-initialized `CachePtr` object and pass the fully-qualified name of the `PdxInstance` object when it becomes deserialized.  It is not important in this part of the exercise;  therefore you can simply provide "Person" as an argument.  You will use the `PdxInstanceFactoryPtr` object to serialize Person's object fields one by one.

g. `(TODO-4)` Write Person object's field `m_name` to the `PdxInstanceFactoryPtr` as String using the `writeString()` method.

h. `(TODO-5)` Write Person object's field `m_id` to the `PdxInstanceFactoryPtr` as Integer using the `writeInt()` method.

i. `(TODO-6)` You will need to mark at least one `Person` class field as an identity field for the GemFire PDX mechanism to differentiate objects correctly.  You should pick the field that uniquely identifies the object.  Mark the `m_id` field of the `Person` class as PDX instance identity field using the `markIdentityField()` method.

j. `(TODO-7)` Now you are ready to create the `PdxInstancePtr` object from the `PdxInstanceFactoryPtr`.  Use its instance method `create()` to instantiate the `PdxInstance` object that is now ready to be stored in GemFire.

k. `(TODO-8)` You can use the normal GemFire API calls to put the `PdxIntancePtr` object to the `Customer` region under key `Key3` as is.  GemFire will automatically recognize the object type and will store it on the server side in the PDX form ready for clients on other platforms to access its data.

l. `(TODO-9)` We will now read the stored `PdxInstance` object back from the GemFire server and compare retrieved values with the ones that we have used at object creation.  Add the code to read the value stored under the key `Key3` from the `Customer` region as `PdxInstancePtr` object.  Use the already-defined `regionPtr` object for that.

m. `(TODO-10)` After you have retrieved the `PdxInstancePtr` corresponding to the value that was stored earlier, read the `m_id`, `m_age`, and `m_name` fields form the `PdxInstancePtr` object into the `id`, `age`, and `name` variables defined at this place.  The following code performs conditional check to verify that the retrieved field values are equal to the test values that were used during initial `PdxInstance` object creation.  It must output a success message to the application's standard out log stream when you build and run the test application.


=== Store PDX data from the Java client application

a. You are now going to access values in the GemFire cache that were stored by an application running on another platform.  That will be a sample Java application from the "Data Serialization" lab of the main "GemFire Developer" course.  We assume that you have successfully setup the main "GemFire Developer" course environment on your laptop and have successfully executed the `io.pivotal.bookshop.buslogic.NewCustomerClient` command-line Java application from the `data-serialization` (or `data-serialization-solution`) project.  When run without any parameters this application creates under the key "9999" in the "Customer" region a PDX-serialized value and stores an instance of `io.pivotal.bookshop.domain.Customer` Java class in the GemFire cache.

b.  Check that the Java object has been successfully stored in the "Customer" region by executing the gfsh command:

  get --region=/Customer --key="9999" --key-class=java.lang.Integer

You should output similar to the following:

----
Result      : true
Key Class   : java.lang.Integer
Key         : 9999
Value Class : com.gemstone.gemfire.pdx.internal.PdxInstanceImpl

customerNumber | firstName | lastName | telephoneNumber |                     primaryAddress                      | myBookOrders
-------------- | --------- | -------- | --------------- | ------------------------------------------------------- | -------------------------
123            | John      | Doe      | 512.333.4444    | class com.gemstone.gemfire.pdx.internal.PdxInstanceImpl | class java.util.ArrayList
----

=== Reading PDX values stored by the Java application

a. `(TODO-11)` You will now continue implementation of the `PdxInstance.cpp` application by reading the `PdxInstancePtr` object stored under the key 9999 by the Java application from the main GemFire Developer course's "Data Serialization" lab.  Get that object using the available `regionPtr` object.

b. `(TODO-12)` Read the `PdxInstance` object fields `customerNumber`, `firstName`, `lastName`, and `telephoneNumber` into the pre-defined local variables

c. You are now ready to build the C++ GemFire client application.  Build it in the `lab2-cross-platform` folder, similarly to the way you built `Basic.cpp` in the previous lab:

  g++ -D_REENTRANT -O3 -Wall -m64 -I${GFCPP}/include -L${GFCPP}/lib -Wl,-rpath,${GFCPP}/lib -lgfcppcache PdxInstance.cpp -o PdxInstance

d. The build should create a native executable file `PdxInstance` in the current folder and generate no warnings or errors.

e. `(TODO-13)` Now run the `PdxInstance` application

  ./PdxInstance
+
Observe the console output.  You should see no errors and all log output messages that were added to the application code.
+
Please note that the values of the Customer object with the key "9999" stored by the test Java application are getting also shown correctly and correspond to the values set in the Java application.
+
The console output should look similar to the following:
+
----
[config 2016/11/20 23:50:36.001529 UTC localhost.localdomain:12730 140222677391168] Starting the GemFire Native Client
[info 2016/11/20 23:50:36.001955 UTC localhost.localdomain:12730 140222677391168] Using GFNative_CLbclrplcG12730 as random data for ClientProxyMembershipID
[info 2016/11/20 23:50:36.004461 UTC localhost.localdomain:12730 140222677391168] Xml file parsed successfully
[info 2016/11/20 23:50:36.005847 UTC localhost.localdomain:12730 140222677391168] Creating region Customer attached to pool examplePool
[info 2016/11/20 23:50:36.005940 UTC localhost.localdomain:12730 140222677391168] Declarative configuration of cache completed successfully
[info 2016/11/20 23:50:36.005956 UTC localhost.localdomain:12730 140222677391168] Created the GemFire Cache
[info 2016/11/20 23:50:36.005962 UTC localhost.localdomain:12730 140222677391168] Obtained the Region from the Cache
[info 2016/11/20 23:50:36.005965 UTC localhost.localdomain:12730 140222677391168] ******************* WORKING WITH PDX *******************
[info 2016/11/20 23:50:36.005972 UTC localhost.localdomain:12730 140222677391168] Created PdxInstanceFactory for Person class
[info 2016/11/20 23:50:36.006520 UTC localhost.localdomain:12730 140222677391168] Using socket send buffer size of 64240.
[info 2016/11/20 23:50:36.006530 UTC localhost.localdomain:12730 140222677391168] Using socket receive buffer size of 64240.
[info 2016/11/20 23:50:36.006922 UTC localhost.localdomain:12730 140222591575808] ClientMetadataService started for pool examplePool
[info 2016/11/20 23:50:36.036397 UTC localhost.localdomain:12730 140222677391168] Created PdxInstance for Person class
[info 2016/11/20 23:50:36.038083 UTC localhost.localdomain:12730 140222591575808] Updated client meta data
[info 2016/11/20 23:50:36.056191 UTC localhost.localdomain:12730 140222677391168] Populated PdxInstance Object
[info 2016/11/20 23:50:36.057404 UTC localhost.localdomain:12730 140222677391168] Got PdxInstance Object
[info 2016/11/20 23:50:36.057433 UTC localhost.localdomain:12730 140222677391168] PdxInstance returns all fields value expected
[info 2016/11/20 23:50:36.057438 UTC localhost.localdomain:12730 140222677391168] ******************* READING JAVA VALUES *******************
[info 2016/11/20 23:50:36.058514 UTC localhost.localdomain:12730 140222677391168] Read Customer: customerNumber=9999; firstName=John; lastName=Doe; telephoneNumber=512.333.4444
[info 2016/11/20 23:50:36.058832 UTC localhost.localdomain:12730 140222591575808] ClientMetadataService stopped for pool examplePool
[config 2016/11/20 23:50:36.156802 UTC localhost.localdomain:12730 140222677391168] Stopped the GemFire Native Client
[info 2016/11/20 23:50:36.156839 UTC localhost.localdomain:12730 140222677391168] Closed the GemFire Cache
----


Congratulations!  You have now successfully completed this lab.
